# Add your own folder id (from Google Drive URL)
drive_folder_id="1FgwbjmsWxOpn9m19j6MxmefQH_RFRb9y"

[runtime]
log_level="WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/telemetry
dlthub_telemetry = true
